runtime: go111
automatic_scaling:
  min_instances: 0
  max_instances: 1
env_variables:
  TELEGRAM_TOKEN: 'TELEGRAM_TOKEN'
  APP_URL: 'APP_URL'
  SMMRY_KEY: 'SMMRY_KEY'
  SPOTIFY_ID: 'SPOTIFY_ID'
  SPOTIFY_SECRET: 'SPOTIFY_SECRET'
  ALLOWED_CHAT_ID: 'ALLOWED_CHAT_ID'
